version: '3'      
services:
   db:
     image: mysql:5.7
     volumes:
       - /data/db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: n4v4
       MYSQL_DATABASE: wordpress
       MYSQL_USER: n4v4
       MYSQL_PASSWORD: n4v4

   wordpress1:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - /data/web_data:/var/www/html
     ports: 
       - "17777:80"
     expose:
       - 80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: n4v4
       WORDPRESS_DB_PASSWORD: n4v4
   wordpress2:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - /data/web_data:/var/www/html
     ports: 
       - "17778:80"
     expose:
       - 80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: n4v4
       WORDPRESS_DB_PASSWORD: n4v4
   wordpress3:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - /data/web_data:/var/www/html
     ports: 
       - "17779:80"
     expose:
       - 80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: n4v4
       WORDPRESS_DB_PASSWORD: n4v4
   wordpress4:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - /data/web_data:/var/www/html
     ports: 
       - "17780:80"
     expose:
       - 80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: n4v4
       WORDPRESS_DB_PASSWORD: n4v4
   haproxy:
     depends_on:
       - wordpress1
       - wordpress2
       - wordpress3
       - wordpress4
     image: haproxy
     volumes:
       - ./haproxy:/usr/local/etc/haproxy
     links:
       - wordpress1
       - wordpress2
       - wordpress3
       - wordpress4
     ports:
       - "8080:80" 
     expose:
       - 80  
